site_name: chic


theme:
  name: "material"


plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          selection:
            filters:
              - "!^_[^_]"

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: "#"
      separator: "_"


extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - Quick start: chic/quickstart.md
  - Neighbour lists: chic/neighbourlists.md

  - Python API:
    - Structure: chic/structure.md
    - Net: chic/net.md
    - AtomicCluster: chic/atomiccluster.md

  - Examples:
      - Coarse-graining basics: chic/examples/coarse-graining.md
      - Removing disorder: chic/examples/disorder.md
      - Decorating basics: chic/examples/decorating.md
      - Trajectories: chic/examples/trajectories.md
      - Atomic energies: chic/examples/atomic_energies.md


extra_css:
  - css/style.css
  - css/material.css
  - css/mkdocstrings.css
  - css/insiders.css