site_name: chic


theme:
  name: "material"


plugins:
  - search


markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: "#"
      separator: "_"


extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - Quick start: chic/quickstart.md
  - Neighbour lists: chic/neighbourlists.md

  - Examples:
      - Basic usage: chic/examples/basics.md
      - Trajectories: chic/examples/trajectories.md
      - Atomic energies: chic/examples/atomic_energies.md